name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Run tests
      run: swift test -v
